In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [4]:
dat=pd.read_excel('C:/Users/admin/Downloads/DDWCT-0000C-08A.xlsx', header=1)
dat.head(50)

,table name,state code,town code,town name,rural/urban,Age-group,total pop person,total pop males,total pop females,grad n above persons,...,agri and dairy females,vet persons,vet males,vet females,teaching persons,teaching males,teaching females,other persons,other males,other females
0,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,Total,878906,458640,420266,135783,...,100,336,276,60,5907,1349,4558,84,48,36
1,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,15-19,114641,58689,55952,0,...,0,0,0,0,0,0,0,0,0,0
2,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,20-24,117922,60661,57261,25190,...,17,36,22,14,1117,172,945,9,3,6
3,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,25-29,117089,60280,56809,30970,...,17,58,36,22,1725,335,1390,25,10,15
4,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,30-34,98397,50448,47949,21496,...,22,30,24,6,823,183,640,24,12,12
5,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,35-59,333020,177235,155785,49950,...,42,153,136,17,1874,466,1408,23,21,2
6,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,60+,96201,50231,45970,8074,...,2,59,58,1,364,191,173,3,2,1
7,C2408A,1,800013,Srinagar (M Corp.+OG),Urban,Age Not stated,1636,1096,540,103,...,0,0,0,0,4,2,2,0,0,0
8,C2408A,1,800033,Anantnag (M Cl+OG),Urban,Total,97195,49119,48076,12666,...,8,22,21,1,1355,436,919,6,3,3
9,C2408A,1,800033,Anantnag (M Cl+OG),Urban,15-19,13828,7238,6590,0,...,0,0,0,0,0,0,0,0,0,0
10,C2408A,1,800033,Anantnag (M Cl+OG),Urban,20-24,13422,6770,6652,2301,...,1,4,4,0,161,44,117,3,1,2
11,C2408A,1,800033,Anantnag (M Cl+OG),Urban,25-29,12435,5945,6490,2734,...,2,2,2,0,304,73,231,1,1,0
12,C2408A,1,800033,Anantnag (M Cl+OG),Urban,30-34,11849,5843,6006,2154,...,3,4,4,0,225,56,169,1,0,1
13,C2408A,1,800033,Anantnag (M Cl+OG),Urban,35-59,35306,18125,17181,4904,...,2,9,9,0,601,207,394,1,1,0
14,C2408A,1,800033,Anantnag (M Cl+OG),Urban,60+,10258,5126,5132,568,...,0,3,2,1,64,56,8,0,0,0
15,C2408A,1,800033,Anantnag (M Cl+OG),Urban,Age Not stated,97,72,25,5,...,0,0,0,0,0,0,0,0,0,0
16,C2408A,1,800071,Jammu (M Corp.+OG),Urban,Total,450316,234098,216218,121564,...,107,342,303,39,7019,1323,5696,108,39,69
17,C2408A,1,800071,Jammu (M Corp.+OG),Urban,15-19,49796,27440,22356,0,...,0,0,0,0,0,0,0,0,0,0
18,C2408A,1,800071,Jammu (M Corp.+OG),Urban,20-24,53846,28079,25767,17347,...,9,41,24,17,562,51,511,40,12,28
19,C2408A,1,800071,Jammu (M Corp.+OG),Urban,25-29,52659,27034,25625,20695,...,9,47,36,11,1056,114,942,31,6,25
20,C2408A,1,800071,Jammu (M Corp.+OG),Urban,30-34,46090,23464,22626,16143,...,55,18,13,5,1103,108,995,14,4,10
21,C2408A,1,800071,Jammu (M Corp.+OG),Urban,35-59,186565,96388,90177,54505,...,33,172,167,5,3413,619,2794,18,13,5
22,C2408A,1,800071,Jammu (M Corp.+OG),Urban,60+,60749,31327,29422,12787,...,1,64,63,1,880,430,450,4,4,0
23,C2408A,1,800071,Jammu (M Corp.+OG),Urban,Age Not stated,611,366,245,87,...,0,0,0,0,5,1,4,1,0,1
24,C2408A,2,800137,Shimla (M Corp.),Urban,Total,134877,74240,60637,43353,...,6,17,12,5,1180,313,867,17,9,8
25,C2408A,2,800137,Shimla (M Corp.),Urban,15-19,16991,9430,7561,0,...,0,0,0,0,0,0,0,0,0,0
26,C2408A,2,800137,Shimla (M Corp.),Urban,20-24,19912,10718,9194,6250,...,0,0,0,0,175,45,130,0,0,0
27,C2408A,2,800137,Shimla (M Corp.),Urban,25-29,16680,9056,7624,7646,...,2,5,2,3,230,64,166,3,2,1
28,C2408A,2,800137,Shimla (M Corp.),Urban,30-34,14781,7800,6981,6116,...,0,0,0,0,179,62,117,3,1,2
29,C2408A,2,800137,Shimla (M Corp.),Urban,35-59,56048,31536,24512,20069,...,4,8,6,2,456,110,346,10,6,4
30,C2408A,2,800137,Shimla (M Corp.),Urban,60+,10271,5583,4688,3223,...,0,4,4,0,140,32,108,1,0,1
31,C2408A,2,800137,Shimla (M Corp.),Urban,Age Not stated,194,117,77,49,...,0,0,0,0,0,0,0,0,0,0
32,C2408A,3,800144,Pathankot (M Cl+OG),Urban,Total,122125,62762,59363,24038,...,2,7,6,1,1876,481,1395,6,2,4
33,C2408A,3,800144,Pathankot (M Cl+OG),Urban,15-19,14369,7947,6422,0,...,0,0,0,0,0,0,0,0,0,0
34,C2408A,3,800144,Pathankot (M Cl+OG),Urban,20-24,15753,8258,7495,4319,...,1,0,0,0,252,25,227,2,1,1
35,C2408A,3,800144,Pathankot (M Cl+OG),Urban,25-29,14725,7512,7213,4617,...,1,1,1,0,287,48,239,3,1,2
36,C2408A,3,800144,Pathankot (M Cl+OG),Urban,30-34,12362,6312,6050,3387,...,0,0,0,0,266,61,205,0,0,0
37,C2408A,3,800144,Pathankot (M Cl+OG),Urban,35-59,47924,24342,23582,9813,...,0,6,5,1,861,230,631,1,0,1
38,C2408A,3,800144,Pathankot (M Cl+OG),Urban,60+,16906,8342,8564,1896,...,0,0,0,0,210,117,93,0,0,0
39,C2408A,3,800144,Pathankot (M Cl+OG),Urban,Age Not stated,86,49,37,6,...,0,0,0,0,0,0,0,0,0,0
40,C2408A,3,800149,Batala (M Cl+OG),Urban,Total,120946,62500,58446,16436,...,3,6,6,0,1170,402,768,9,5,4
41,C2408A,3,800149,Batala (M Cl+OG),Urban,15-19,16009,9025,6984,0,...,0,0,0,0,0,0,0,0,0,0
42,C2408A,3,800149,Batala (M Cl+OG),Urban,20-24,16254,8674,7580,2666,...,2,0,0,0,112,20,92,2,2,0
43,C2408A,3,800149,Batala (M Cl+OG),Urban,25-29,14522,7584,6938,3295,...,0,1,1,0,165,45,120,0,0,0
44,C2408A,3,800149,Batala (M Cl+OG),Urban,30-34,11931,6121,5810,2390,...,0,0,0,0,162,53,109,2,1,1
45,C2408A,3,800149,Batala (M Cl+OG),Urban,35-59,45757,22931,22826,6801,...,1,4,4,0,580,194,386,4,2,2
46,C2408A,3,800149,Batala (M Cl+OG),Urban,60+,16326,8093,8233,1273,...,0,1,1,0,151,90,61,1,0,1
47,C2408A,3,800149,Batala (M Cl+OG),Urban,Age Not stated,147,72,75,11,...,0,0,0,0,0,0,0,0,0,0
48,C2408A,3,800166,Jalandhar (M Corp.+OG),Urban,Total,663953,348525,315428,128924,...,13,55,52,3,6027,1126,4901,26,11,15
49,C2408A,3,800166,Jalandhar (M Corp.+OG),Urban,15-19,81948,46191,35757,0,...,0,0,0,0,0,0,0,0,0,0